{
    "name": "BIKO: Модуль изменяет форму товара для удобства внесения информации",
    "version": "14.0.1.1.4",
    "author": "Borovlev A.S.",
    "company": "BIKO Solutions",
    "depends": [
        "stock",
        "sale",
        "sale_stock",
        "sale_timesheet",
        "purchase",
        "product",
        "product_brand",
        "biko_add_product_class",
        "biko_add_product_prefix",
        "website_sale",
        "website_sale_stock",
        "droggol_theme_common",
        "stock_landed_costs",
        "product_attribute_set_completeness",
        "product_attribute_set",
        "account",
        "simbioz_uktzed",
        "product_custom_info",
        "account",
        "base_accounting_kit",
        "pim",
        "product_multiple_barcodes",
        "muztorg_purchase_subscription",
    ],
    "data": [
        "views/product_views.xml",
    ],
    "license": "LGPL-3",
    "installable": True,
    "application": True,
    "auto_install": False,
}
